### ISSUE TITLE
Index error List out of range...

### ISSUE THREAD

**Issue by JVTEAM** [AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword#2]
Running on a jetson nano jetpack 4.4

python3.7 mic_streaming.py --keywords blueberry
Traceback (most recent call last):
  File "mic_streaming.py", line 35, in <module>
    import pvporcupine
  File "/home/vondalej/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 2, in <module>
    from .resources.util.python import *
  File "/home/vondalej/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/__init__.py", line 1, in <module>
    from .util import KEYWORDS
  File "/home/vondalej/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/util.py", line 43, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/home/vondalej/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/util.py", line 36, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/home/vondalej/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/util.py", line 12, in _pv_linux_machine
    hardware_info = [x for x in cpu_info.split('\n') if 'Hardware' in x][0]
IndexError: list index out of range

**Comment by AIWintermuteAI** [comment]
This code is for Raspberry Pi. Jetson Nano has a different CPU and it is not supported by porcupine yet. See
https://github.com/Picovoice/porcupine/issues/222
https://github.com/Picovoice/Porcupine/issues/181
As a solution you might try different ARM build binaries or use a different hot word detector.
Closing the issue now - if you do find a solution, please post it here.

**Comment by hackebike** [comment]
I got the same error.
The Picovoice team told me that they do not support Raspberry PI 4 OS 64 bit at this time.
So no luck for now!
